### ISSUE TITLE
Հարցերի փոխարեն

### ISSUE THREAD

**Issue by antaranyan** [hisusqristos/arch-elmitecture#2]
Իմ և իմ նման այլ հեռուստադիտողների անունից խնդրում եմ օգտագործեք նաև "ռեպերտուար" բառը․

Շնորհակալություն ամեն ինչի համար

**Comment by hisusqristos** [comment]
https://youtu.be/sSnlx1PDehY?si=SHz8GYIB-3iWDwAj
